CREATE TABLE GEOCODES
(
ID INTEGER NOT NULL,
CITY_NAME VARCHAR(2147483647) NOT NULL,
LATITUDE DOUBLE NOT NULL,
LONGITUDE DOUBLE NOT NULL,
COUNTRY_CODE VARCHAR(2147483647) NOT NULL
);
CREATE UNIQUE INDEX UNIQUE_ID_INDEX_1 ON GEOCODES (ID);

CREATE TABLE COUNTRYCODES
(
COUNTRY_CODE VARCHAR(10) NOT NULL,
LATITUDE DOUBLE NOT NULL,
LONGITUDE DOUBLE NOT NULL,
NAME VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX UNIQUE_ID_INDEX_1 ON COUNTRYCODES (COUNTRY_CODE);
